#!/usr/bin/env bash

sudo apt-get -y update
sudo apt-get install -y nginx
sudo systemctl start nginx

sudo sh -c "echo 'server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;

	location / {
		return 200 \"Hello World!\n\";
	}
}' > /etc/nginx/sites-available/default"

sudo service nginx restart
