#!/usr/bin/env bash
# Displays the content of the file /etc/passwd
# Only displays username, user id and Home dir path for user

while IFS= read -r LINE; do
    echo "$LINE" | cut -d':' -f1,4,7
done < /etc/passwd

